# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/RedisGraph/graph-database-benchmark/benchmark/redisgraph
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

  queryset:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/RedisGraph/graph-database-benchmark/benchmark/redisgraph
    steps:
      - checkout
      - run: make queries

  benchmark:
    working_directory: /go/src/github.com/RedisGraph/graph-database-benchmark/benchmark/redisgraph
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Spin up RedisGraph container with dataset
          command: |
            make dataset_docker
          no_output_timeout: 40m

#  build-multiarch-docker:
#    machine:
#      enabled: true
#    steps:
#      - checkout
#      - run: |
#          echo "$DOCKER_REDISBENCH_PWD" | base64 --decode | docker login --username $DOCKER_REDISBENCH_USER --password-stdin
#      - run:
#          name: Build
#          command: |
#            make -C benchmark/redisgraph docker-release
#          no_output_timeout: 20m

workflows:
  version: 2
  commit:
    jobs:
      - build
      - queryset
      - benchmark
#    jobs:
#      - build-multiarch-docker:
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              only: master
